version: '3'
services:
  database:
    container_name: wordpress-db
    image: mariadb
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    networks:
      - backend
    restart: always
  wordpress:
    container_name: wordpress-app
    image: wordpress:php7.4-fpm-alpine
    volumes:
      - ./data/wordpress:/var/www/html
    depends_on:
      - database
    environment:
      WORDPRESS_DB_HOST: database
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: wp_
    networks:
      - frontend
      - backend
    restart: always
  nginx:
    container_name: wordpress-web
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/log/nginx:/var/log/nginx
      - ./data/wordpress:/var/www/html
    ports:
      - ${NGINX_HOST_PORT}:80
    networks:
      - frontend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
