name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set basic authentication
      run: echo "test:$(openssl passwd -apr1 test)" >> "./nginx/.htpasswd"
    - name: Build the Docker image
      run: |
        docker build . --file ./mariadb/Dockerfile --tag wordpress-db:$(date +%s)
        docker build . --file ./wordpress/Dockerfile --tag wordpress-app$(date +%s)
        docker build . --file ./nginx/Dockerfile --tag wordpress-web:$(date +%s)
