name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Set basic authentication
      run: echo "test:$(openssl passwd -apr1 test)" >> "./nginx/.htpasswd"
    - name: Build web image
      uses: docker/build-push-action@v4
      with:
        context: ./nginx
        push: false
        tags: wordpress-web:latest
        cache-from: type=gha,scope=web
        cache-to: type=gha,mode=max,scope=web
    - name: Build app image
      uses: docker/build-push-action@v4
      with:
        context: ./wordpress
        push: false
        tags: wordpress-app:latest
        cache-from: type=gha,scope=app
        cache-to: type=gha,mode=max,scope=app
    - name: Build database image
      uses: docker/build-push-action@v4
      with:
        context: ./mariadb
        push: false
        tags: wordpress-db:latest
        cache-from: type=gha,scope=db
        cache-to: type=gha,mode=max,scope=db
